-- V1 : schéma initial. Doit rester identique au diagramme docs/diagrammes/D2-modele-donnees.md.
-- Ne jamais modifier une migration poussée : ajouter V2, V3…

CREATE TABLE promotion (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(150) NOT NULL,
    promotion_id  BIGINT NOT NULL REFERENCES promotion (id)
);

CREATE TABLE session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(200) NOT NULL,
    promotion_id   BIGINT NOT NULL REFERENCES promotion (id),
    code           VARCHAR(6) NOT NULL,                          -- RG20 : unicité parmi les codes non expirés (service)
    ouverture_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at  TIMESTAMP WITH TIME ZONE NOT NULL,            -- RG1 : ouverture_at + 15 min
    statut         VARCHAR(20) NOT NULL DEFAULT 'OUVERTE',
    cloture_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_session_statut CHECK (statut IN ('OUVERTE', 'CLOTUREE'))
);
CREATE INDEX ix_session_code ON session (code);

CREATE TABLE presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session (id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant (id),
    source       VARCHAR(10) NOT NULL,
    marquee_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),   -- RG3
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))   -- Q14
);

CREATE TABLE tentative_code (
    etudiant_id         BIGINT PRIMARY KEY REFERENCES etudiant (id),           -- RG4
    echecs_consecutifs  INT NOT NULL DEFAULT 0,
    bloque_jusqu_a      TIMESTAMP WITH TIME ZONE
);

CREATE TABLE exercice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session (id),
    auteur_id    BIGINT NOT NULL REFERENCES etudiant (id),
    lien         VARCHAR(2048) NOT NULL,                                        -- RG17
    statut       VARCHAR(25) NOT NULL,
    depose_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    modifie_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_exercice_session_auteur UNIQUE (session_id, auteur_id),      -- RG13
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU'))
);

CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL REFERENCES exercice (id),
    relecteur_id  BIGINT NOT NULL REFERENCES etudiant (id),                     -- RG5/RG7 vérifiées par le service
    note          INT,
    commentaire   TEXT,
    assignee_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    rendue_at     TIMESTAMP WITH TIME ZONE,                                     -- non NULL = définitive (RG10)
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),                      -- RG6
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note BETWEEN 0 AND 20)) -- RG9
);
