-- V3 : sécurité (changement de besoin #54). Doit rester identique à D2 (tables UTILISATEUR, FORMATEUR_PROMOTION).
-- Mots de passe stockés en BCrypt (ENF10), jamais en clair.

ALTER TABLE etudiant ADD COLUMN actif BOOLEAN NOT NULL DEFAULT TRUE;                -- RG28

CREATE TABLE utilisateur (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login                      VARCHAR(50) NOT NULL,
    mot_de_passe_hash          VARCHAR(100) NOT NULL,
    role                       VARCHAR(10) NOT NULL,
    nom_affiche                VARCHAR(150) NOT NULL,
    etudiant_id                BIGINT REFERENCES etudiant (id),
    actif                      BOOLEAN NOT NULL DEFAULT TRUE,                       -- RG28
    doit_changer_mot_de_passe  BOOLEAN NOT NULL DEFAULT FALSE,                      -- RG23
    echecs_connexion           INT NOT NULL DEFAULT 0,                              -- RG24
    bloque_jusqu_a             TIMESTAMP WITH TIME ZONE,
    cree_at                    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_utilisateur_login UNIQUE (login),                                 -- RG27
    CONSTRAINT uk_utilisateur_etudiant UNIQUE (etudiant_id),                        -- HYP-15
    CONSTRAINT ck_utilisateur_role CHECK (role IN ('ADMIN', 'FORMATEUR', 'ETUDIANT')),
    CONSTRAINT ck_utilisateur_etudiant CHECK (role <> 'ETUDIANT' OR etudiant_id IS NOT NULL)
);

CREATE TABLE formateur_promotion (
    utilisateur_id  BIGINT NOT NULL REFERENCES utilisateur (id),
    promotion_id    BIGINT NOT NULL REFERENCES promotion (id),
    PRIMARY KEY (utilisateur_id, promotion_id)                                      -- RG26
);

-- Compte administrateur par défaut (EF18) : admin / admin, changement obligatoire à la première connexion (RG23).
-- Comptes de démonstration (README) : formateur / Formateur48 ; awa, paul, lina / Etudiant48.
INSERT INTO utilisateur (login, mot_de_passe_hash, role, nom_affiche, doit_changer_mot_de_passe, cree_at)
VALUES ('admin', '$2b$10$PMy4bStxnlqbQrZl8PiBEOrF1BPTLUJueLb1pvW1Uad6FvvHLvjHq', 'ADMIN', 'Administrateur', TRUE, CURRENT_TIMESTAMP),
       ('formateur', '$2b$10$IH4c4W70nNt/EuDKGOz17.3DkmASO0z04YW2519RaBvCpslEcOUL.', 'FORMATEUR', 'Jean Fokam', FALSE, CURRENT_TIMESTAMP);

INSERT INTO utilisateur (login, mot_de_passe_hash, role, nom_affiche, etudiant_id, cree_at)
SELECT x.login, x.hash, 'ETUDIANT', e.nom, e.id, CURRENT_TIMESTAMP
FROM (VALUES ('awa', 'Awa Ndiaye', '$2b$10$PylqKUsKL5YrdwmM84BYDuCJOvuz/JnEMrbkZmLS1E5Oi8l5Dm.M2'),
             ('paul', 'Paul Mbarga', '$2b$10$5j7TNCdMJ7v7UQU6OJ2sqell/BJndEx2DlftdKXHTzr44nichhmv.'),
             ('lina', 'Lina Kamga', '$2b$10$Nf5aFixo9o1xzI3qXM6fsOFjNK.sp/0jH0U9b6ulaWH1lmHSemrXa')) AS x(login, nom, hash)
JOIN etudiant e ON e.nom = x.nom;

INSERT INTO formateur_promotion (utilisateur_id, promotion_id)
SELECT u.id, p.id FROM utilisateur u CROSS JOIN promotion p
WHERE u.login = 'formateur' AND p.nom = 'P1-2026';
